### ISSUE TITLE
Testi territoriali pubblici prima della prova?

### ISSUE THREAD

**Issue by ABeltramo** [olimpiadi-informatica/oii#4]
I testi per i territoriali 2017 che sono visibili dal repository sono relativi alla prova che si deve ancora svolgere in data 11 aprile 2017?

**Comment by wil93** [comment]
Ciao :smile: 

No, le territoriali dell'11 aprile 2017 fanno parte del ciclo di selezione che porta a partecipare alle IOI 2018 di Tokyo, quindi finiranno nella cartella `2018/` quando saranno pubblicati.

Tra l'altro, non solo non sono pubblici, ma quei task ancora non esistono :sweat_smile:
