### ISSUE TITLE
[2016] Compilazione LaTeX non riuscita

### ISSUE THREAD

**Issue by ABeltramo** [olimpiadi-informatica/oii#5]
Ho dovuto modificare parecchio il codice LaTeX dei territoriali 2016 per poterlo compilare correttamente. Ad esempio manca `\documentclass` ed i file .asy possono essere inclusi tramite `\asyinclude` invece che compilarli in pdf e poi includerli.
Mi manca qualche package o utilizzi qualche utility particolare per la compilazione?
[Esempio disuguaglianze](https://it.sharelatex.com/project/58b3eeb762e902a41ba6cc1c), ho commentato le parti modificate rispetto all'originale per ottenere il risultato in PDF.

**Comment by wil93** [comment]
Il link postato sembra richiedere un'autorizzazione per essere visualizzato :confused: 

Comunque sì per alcuni testi (da 2016 in su) è necessario usare un tool apposito per compilare i testi: https://github.com/algorithm-ninja/cmsbooklet (c'è un README su come usarlo)

A dire il vero non escludo nemmeno che in futuro il formato dei testi cambierà nuovamente :sweat_smile:
