### ISSUE TITLE
Impossibile importare le task in CMS

### ISSUE THREAD

**Issue by ABeltramo** [olimpiadi-informatica/oii#6]
Avrei bisogno una mano per importare le task all'interno di CMS. Ho installato il tool e sono riuscito ad importare correttamente il contest *con_test*.
Volevo provare ad importare uno qualsiasi dei task dei regionali presenti su questo repository ma il comando **cmsImportTask** fallisce.
```
~$ cmsImportTask oii/2016/territoriali/footing/
2017-03-19 11:11:33,260 - INFO [<unknown>] Using configuration file /usr/local/etc/cms.conf.
2017-03-19 11:11:33,666 - INFO [<unknown>] Loading parameters for task footing.
2017-03-19 11:11:33,667 - CRITICAL [<unknown>] Couldn't find any task statement, aborting.
```

**Comment by wil93** [comment]
Ciao, come indicato nell'errore a linea di comando, manca il testo del problema (task statement).

Un modo facile per risolvere è mettere manualmente un file di nome `testo.pdf` nella cartella `testo/` del task (la stessa cartella dove si trova il file `italian.tex`).

Per generare da zero quel file, è necessario usare il tool [cmsbooklet](https://github.com/algorithm-ninja/cmsbooklet) (quando è presente `testo.tex`, invece, basta eseguire `cmsMake testo/testo.pdf` senza installare altri tool).
